[package]
name = "backend"
version = "1.2.1"
edition = "2024"

[dependencies]
indexmap = "2.12.1"
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = { version = "1.0.145", features = ["raw_value"] }
time = { version = "0.3.49", features = ["formatting", "local-offset", "macros", "parsing"] }
